---
name: Matterbridge
description: Populate your Home Assistant instance as Matter Bridge
slug: matterbridge
version: 0.0.7
image: ghcr.io/t0bst4r/matterbridge-home-assistant-addon/{arch}
options:
  home_assistant_client_config: "{}"
schema:
  home_assistant_client_config: str
homeassistant_api: true
host_network: true
webui: http://[HOST]:[PORT:8283]/
init: false
arch:
  - amd64
  - armv7
  - aarch64
map:
  - addon_config:rw
