---
name: Pull Request Build

# yamllint disable-line rule:truthy
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  information:
    name: ℹ️ Addon Information
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.information.outputs.name }}
      description: ${{ steps.information.outputs.description }}
      target: ${{ steps.information.outputs.target }}
      build: ${{ steps.information.outputs.build }}
      architectures: ${{ steps.information.outputs.architectures }}
      version: pr-${{ github.event.number }}
    steps:
      - name: ⤵️ Checkout
        uses: actions/checkout@v4
      - name: ℹ️ Gather Information
        id: information
        uses: frenck/action-addon-information@v1.4.2

  lint:
    name: ✏️ Lint
    needs: [ information ]
    uses: ./.github/workflows/wf-lint.yaml
    permissions:
      pull-requests: read
      contents: read
    with:
      addon-path: "${{ needs.information.outputs.target }}"
      yamllint-config: ".yamllint.yaml"
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: 🚀 Build
    needs: [ information, lint ]
    uses: ./.github/workflows/wf-docker-build.yaml
    strategy:
      matrix:
        architecture: ${{ fromJson(needs.information.outputs.architectures) }}
    with:
      addon-architecture: ${{ matrix.architecture }}
      addon-path: ${{ needs.information.outputs.target }}
      addon-version: ${{ needs.information.outputs.version }}
      addon-name: ${{ needs.information.outputs.name }}
      addon-description: ${{ needs.information.outputs.description }}
      docker-tags: |
        ghcr.io/${{ github.repository }}/${{ matrix.architecture }}:${{ needs.information.outputs.version }}
