---
name: Release

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          config-file: .github/release-please-config.json
          manifest-file: .github/release-please-manifest.json

  information:
    if: ${{ needs.release-please.outputs.release_created }}
    name: ℹ️ Addon Information
    needs: [ release-please ]
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.information.outputs.name }}
      description: ${{ steps.information.outputs.description }}
      target: ${{ steps.information.outputs.target }}
      build: ${{ steps.information.outputs.build }}
      architectures: ${{ steps.information.outputs.architectures }}
      version: ${{ steps.information.outputs.version }}
      environment: latest
    steps:
      - name: ⤵️ Checkout
        uses: actions/checkout@v4
      - name: ℹ️ Gather Information
        id: information
        uses: frenck/action-addon-information@v1.4.2

  build:
    if: ${{ needs.release-please.outputs.release_created }}
    name: 🚀 Build
    needs: [ release-please, information ]
    uses: ./.github/workflows/wf-docker-build.yaml
    strategy:
      matrix:
        architecture: ${{ fromJson(needs.information.outputs.architectures) }}
    with:
      addon-architecture: ${{ matrix.architecture }}
      addon-path: ${{ needs.information.outputs.target }}
      addon-version: ${{ needs.information.outputs.version }}
      addon-name: ${{ needs.information.outputs.name }}
      addon-description: ${{ needs.information.outputs.description }}
      docker-tags: |
        ghcr.io/${{ github.repository }}/${{ matrix.architecture }}:${{ needs.information.outputs.version }}
        ghcr.io/${{ github.repository }}/${{ matrix.architecture }}:${{ needs.information.outputs.environment }}
      docker-push: true
